Add meditation functionality
aceuganda/epilepsy-smart-app pull request #36
Opened 2023-02-22 12:49 UTC by khalifan-kfan

PR Checklist (Make sure these options are checked before raising the PR)

- [ ] - Latest `master` branch merged
- [ ] - Descriptive PR title (can be used in release notes)

#### Summary of Changes (What does this PR do?)
- Adds meditation functionality and esau link

#### Is this change ready to hit production in its current state?
- [x] Yes
- [ ] No

#### Jira Ticket(s) Number
- [SA-79]
- [SA-78]

## Screenshots/Videos

![image](https://user-images.githubusercontent.com/69305400/220623789-bca27fb3-0b47-4a65-a2ed-e4029a2a9080.png)
![image](https://user-images.githubusercontent.com/69305400/220623928-78e16d1e-4133-429b-b23c-b212d44c586b.png)
![image](https://user-images.githubusercontent.com/69305400/220624205-b1018c2d-5e97-46d3-a9e2-8da05acd68f5.png)

2023-02-22 18:11 UTC, FaithDaka requested changes
Great work @khalifan-khan 
Make changes as required. Lint your files using prettier before making commits.

2023-02-22 18:11 UTC, FaithDaka commented on src/pages/ResilienceActivities/Activities/Meditation/meditation.jsx
> +import { ReactComponent as MeditaionBigIcon } from '../../../../assets/svg/Resilience/meditationBigIcon.svg';
Typo here with the word Meditation

2023-02-22 18:11 UTC, FaithDaka commented on src/pages/ResilienceActivities/AllActivitiesPage.jsx
> +import { ReactComponent as Meditaion } from '../../assets/svg/Resilience/meditationIcon.svg';
Typo here with the word Meditation

2023-02-22 19:03 UTC, khalifan-kfan commented on src/pages/MedicineTracking/IntroPage.jsx
> +          <Largebtn title="Record Your Medication" link="/medication/assessment/0" />
yes it does as per the new designs

2023-02-22 19:07 UTC, khalifan-kfan commented
Thanks for the feedback @FaithDaka, would you please re-review.

2023-02-28 06:52 UTC, FaithDaka approved these changes

2023-02-28 06:55 UTC, merged